function plotClusterLines(h, clusters, options)
% plotClusterLines - Overlay horizontal lines for clusters on a plot with time-axis
%
%   plotClusterLines parses the significance clusters generated by the ClustME 
%   engine and overlays horizontal significance bars on an existing time-domain 
%   plot (e.g., an ERP or difference wave). It supports custom formatting, 
%   dynamic vertical positioning, and automatic p-value annotation.
%
% Syntax:
%   plotClusterLines(h, clusters)
%   plotClusterLines(h, clusters, Name, Value)
%
% Inputs:
%   h          - [handle] Figure or axes object containing an existing time-based plot.
%   clusters   - [1×K struct] Array detailing each surviving cluster with fields:
%       .type           ['positive' | 'negative'] Direction of the effect.
%       .start, .end    [double] Sample indices of the cluster boundaries.
%       .p_value        [double] FWER-corrected permutation p-value.
%
% Options (Name-Value arguments):
%   .color               [char]    Line and text color. (Default: 'k')
%   .onlyShowSignificant [logical] Filter clusters by alpha. (Default: true)
%   .alpha               [double]  Significance threshold. (Default: 0.05)
%   .pvals               [char]    Annotation style: 'none', 'stars', 'values'. (Default: 'none')
%   .fontSize            [double]  Numeric override for annotation text size. (Default: [])
%   .posYshift           [double]  Vertical offset fraction for positive clusters. (Default: 0.08)
%   .negYshift           [double]  Vertical offset fraction for negative clusters. (Default: 0.34)
%   .valuesShift         [double]  Vertical offset for numeric p-value text. (Default: 0.05)
%   .starsShift          [double]  Vertical offset for asterisk p-value text. (Default: 0.02)
%
% Outputs:
%   None (Modifies the target axes in place).
%
% Dependencies:
%   - MATLAB R2019b or newer.
%   - ClustME Package (+clustme).
%
% Reference:
%   Yona, G., & Magill, P. J. Fast Cluster-Based Permutation Testing with 
%   Linear Mixed-Effects Models.
%
% Version: 1.0.0
% Last Modified: 01 May 2026
%
% Copyright (C) 2026 University of Oxford
% Author: Guy Yona
%
% This program is free software: you can redistribute it and/or modify
% it under the terms of the GNU General Public License as published by
% the Free Software Foundation, either version 3 of the License, or
% (at your option) any later version.
%
% This program is distributed in the hope that it will be useful,
% but WITHOUT ANY WARRANTY; without even the implied warranty of
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
% GNU General Public License for more details.
%
% You should have received a copy of the GNU General Public License
% along with this program.  If not, see <https://www.gnu.org/licenses/>.
 
    arguments
        h                            {mustBeA(h, {'matlab.ui.Figure','matlab.graphics.axis.Axes'})}
        clusters                     struct
        options.color               (1,:) char = 'k'
        options.onlyShowSignificant (1,1) logical = true
        options.alpha               (1,1) double {mustBePositive, mustBeLessThanOrEqual(options.alpha,1)} = 0.05
        options.pvals               (1,:) char {mustBeMember(options.pvals,{'none','stars','values'})} = 'none'
        options.fontSize            double = []
        options.posYshift           double = 0.08
        options.negYshift           double = 0.34
        options.valuesShift         double = 0.05
        options.starsShift          double = 0.02
    end

    % Line width parameter
    lineWidth = 3;

    % Determine target axes
    if isgraphics(h, 'figure')
        axs = findall(h, 'Type', 'axes');
        if isempty(axs)
            ax = axes('Parent', h);
        else
            ax = axs(1);
        end
    else
        ax = h;
    end

    % Activate axes
    axes(ax); hold(ax, 'on');

    % Infer time axis from first plotted line
    lines = findobj(ax, 'Type', 'line');
    if isempty(lines)
        error('No line objects found in target axes to infer time axis.');
    end
    xdata = get(lines(end), 'XData');
    M = numel(xdata);

    % Determine y positions and ranges
    ylims   = ax.YLim;
    y_range = diff(ylims);
    y_pos   = ylims(2) - options.posYshift * y_range;
    y_neg   = ylims(1) + options.negYshift * y_range;

    % Plot horizontal lines and annotations for each cluster
    for k = 1:numel(clusters)
        c = clusters(k);
        % Optionally skip non-significant clusters
        if options.onlyShowSignificant && c.p_value >= options.alpha
            continue;
        end
        % Skip clusters out of plotted range
        if c.start < 1 || c.end > M
            continue;
        end
        % Map indices to time values
        x_start = xdata(c.start);
        x_end   = xdata(c.end);

        % Choose vertical line position
        if strcmp(c.type, 'positive')
            y_line = y_pos;
            sign = 1;
        else
            y_line = y_neg;
            sign = -0.7;
        end

        % Draw horizontal line
        plot(ax, [x_start, x_end], [y_line, y_line], 'Color', options.color, 'LineWidth', lineWidth);

        % Annotate p-value if requested
        if ~strcmp(options.pvals, 'none')
            switch options.pvals
                case 'stars'
                    y_text = y_line + options.starsShift * sign * y_range;
                    if c.p_value < 0.001
                        str = '***';
                    elseif c.p_value < 0.01
                        str = '**';
                    elseif c.p_value < options.alpha
                        str = '*';
                    else
                        str = '';
                    end
                    fontSize = 18;
                case 'values'
                    y_text = y_line + options.valuesShift * sign * y_range;
                    if c.p_value < 0.001
                        str = '$p < 0.001$';
                    else
                        str = sprintf('$p = %.3f$', c.p_value);
                    end
                    fontSize = 13;
                otherwise
                    str = '';
            end
            if ~isempty(str)
                if ~isempty(options.fontSize)
                    fontSize = options.fontSize;
                end
                text(ax, mean([x_start, x_end]), y_text, str, ...
                     'HorizontalAlignment', 'center', 'FontSize', fontSize, 'Color', options.color, 'Interpreter', 'latex');
            end
        end
    end

    hold(ax, 'off');
    drawnow;
end
