% run_accuracy_speed_validation - Validation suite for Static-V approximation
%
%   This script benchmarks the mathematical fidelity and computational efficiency 
%   of the Static-V algorithm against a full iterative Linear Mixed-Effects (LME) 
%   refit. This is a scientific validation script designed to generate empirical 
%   evidence for the manuscript, distinct from routine software unit tests.
%
% Syntax:
%   run_accuracy_speed_validation()
%
% Validation Targets:
%   1. Fidelity: Evaluates the correlation (R^2), slope, and Mean Absolute Deviation 
%      (MAD) between t-statistics generated by Static-V and the full LME over a 
%      batch of simulated datasets.
%   2. Efficiency: Extrapolates the execution time of full LME refitting to 
%      quantify the multiplicative speedup factor achieved by Static-V.
%
% Outputs:
%   - Terminal: Summary statistics (R^2, Slope, Intercept, MAD) and speedup factor.
%   - Figures: Figure 2 (Panel A: Identity, Panel B: Fidelity Metrics, Panel C: Speedup).
%
% Dependencies:
%   - MATLAB R2019b or newer.
%   - validation_settings.json (for export directory configuration).
%   - Part of the ClustME Validation Suite.
%
% Reference:
%   Yona, G., & Magill, P. J. Fast Cluster-Based Permutation Testing with
%   Linear Mixed-Effects Models.
%
% Version: 1.0.0
% Last Modified: 7 May 2026
%
% Copyright (C) 2026 G. Yona% Copyright (C) 2026 University of Oxford
% Author: Guy Yona
%
% This program is free software: you can redistribute it and/or modify
% it under the terms of the GNU General Public License as published by
% the Free Software Foundation, either version 3 of the License, or
% (at your option) any later version.
%
% This program is distributed in the hope that it will be useful,
% but WITHOUT ANY WARRANTY; without even the implied warranty of
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
% GNU General Public License for more details.
%
% You should have received a copy of the GNU General Public License
% along with this program.  If not, see <https://www.gnu.org/licenses/>.

clear; clc; close all;

%% 1. Configuration
nDatasets   = 25;
nSubjects   = 20; 
nTrials     = 30;

% --- Export Configuration ---
settings = jsondecode(fileread('validation_settings.json'));

exportDir = settings.exportDir;
baseFileName = 'Figure2-ABC';

% --- Execution Mode Switch ---
switch settings.runMode
    case 'debug'
        nPerms_Static = 100;   % Target permutation count for the Static-V benchmark
        nPerms_Full   = 10;    % Subsample used to extrapolate full-LME runtime
        nDatasets     = 3;
        fprintf('Mode: DEBUG (Fast mechanical test)\n');
        
    case 'fast'
        nPerms_Static = 5000;
        nPerms_Full   = 50;
        fprintf('Mode: FAST (Extrapolating Full LME speed)\n');
        
    case 'publication'
        % Full rigorous run without extrapolation 
        nPerms_Static = 5000;
        nPerms_Full   = 5000;
        fprintf('Mode: PUBLICATION (Full iterative LME refits)\n');
        
    otherwise
        error('Unknown runMode "%s". Use "debug","fast", or "publication"', settings.runMode);
end

% Formula: Simple random-intercept model
lmeFormula  = 'response ~ 1 + (1|Subject)';

% Parameter ranges for stress-testing
range_SubjVar  = [0.5, 5.0];   % Magnitude of random intercepts
range_Ramp     = [1.0, 5.0];   % Steepness of non-stationary noise ramp

% Storage for batch metrics
results = repmat(struct('dataset', 0, 'corr', 0, 'slope', 0, 'intercept', 0, 'MAD', 0), nDatasets, 1);

% Storage for raw T-maps
batch_T_full   = cell(nDatasets, 1);
batch_T_static = cell(nDatasets, 1);

fprintf('========================================================\n');
fprintf('     Running Accuracy Batch (N=%d Datasets)\n', nDatasets);
fprintf('Comparing "Static-V" (Approximation) vs "Full Fit" (Exact)\n');
fprintf('========================================================\n\n');

%% 2. The Validation Loop
for d = 1:nDatasets
    
    % A. Randomize Stress-Test Parameters
    % We vary the Random Effect structure and the Noise Non-stationarity
    % to ensure the approximation holds across different data shapes.
    thisSubjVar = range_SubjVar(1) + rand * diff(range_SubjVar);
    thisRamp    = range_Ramp(1) + rand * diff(range_Ramp);
    
    config = struct('designType', 'one-sample', ...
                    'nTrials', nTrials, ...
                    'effectSize', 0.5); % Moderate signal to drive T-stats away from 0
    
    % B. Generate Data
    % We use 'complex' noise to trigger the non-stationary ramp logic
    [responses, designTable, ~] = clustme.bench_generator(nSubjects, config, ...
        'noiseMode', 'complex', ...
        'SubjectVar', thisSubjVar, ...
        'RampStrength', thisRamp, ...
        'RandomSeed', 1000 + d); % for reproducibility
        
    fprintf('Dataset %d/%d [Var: %.2f, Ramp: %.2f]... ', d, nDatasets, thisSubjVar, thisRamp);
        
    % C. Run Full LME Refit Loop
    % We disable permutations (numPerms=0) because we only need the observed T-map.
    [~, ~, vis_full] = ClustME(responses, designTable, lmeFormula, ...
        'fullLME', true, ...       
        'parallel', true, ...
        'numPerms', 0, ...       
        'verbose', false);
    
    % D. Run Static-V approximation
    % We use 'adaptiveLocal' mode as it is the intended default for complex noise.
    [~, ~, vis_static] = ClustME(responses, designTable, lmeFormula, ...
        'fullLME', false, ...      
        'Vmode', 'adaptiveLocal', ...
        'parallel', true, ...
        'numPerms', 0, ...
        'verbose', false);
        
    % E. Calculate Fidelity Metrics
    T_full   = vis_full.Tmap;
    T_static = vis_static.Tmap;
    
    % 1. Correlation (Pearson)
    results(d).corr = corr(T_full(:), T_static(:));
    
    % 2. Linear Fit (y = mx + c)
    % Ideally: Slope=1, Intercept=0
    p = polyfit(T_full(:), T_static(:), 1);
    results(d).slope     = p(1);
    results(d).intercept = p(2);
    
    % 3. Mean Absolute Deviation (Error)
    results(d).MAD = mean(abs(T_full - T_static));
    
    % F. Log Results
    results(d).dataset   = d;
    
    batch_T_full{d}   = T_full;
    batch_T_static{d} = T_static;
    
    fprintf('R^2=%.4f | Slope=%.3f | MAD=%.4f\n', results(d).corr^2, results(d).slope, results(d).MAD);
end

%% 3. Permutation Speed Benchmark
fprintf('\n--- Computational Speed Benchmark ---\n');
fprintf('Measuring execution time on a single dataset (N=%d trials)...\n', size(responses,1));

% Use the last dataset generated from the loop as the test case
% 1. Measure Static-V (Full 5,000 Perms)
fprintf('   Running Static-V (%d perms)... ', nPerms_Static);
timer_static = tic;
ClustME(responses, designTable, lmeFormula, ...
    'fullLME', false, ...
    'numPerms', nPerms_Static, ...
    'Vmode', 'adaptiveLocal', ...
    'parallel', true, ...
    'verbose', false);
time_static = toc(timer_static);
fprintf('Done in %.2f s\n', time_static);

% 2. Measure Full LME refit proxy (Small sample to extrapolate)
fprintf('   Running Full LME refit Proxy (%d perms)... ', nPerms_Full);
timer_full = tic;
ClustME(responses, designTable, lmeFormula, ...
    'fullLME', true, ...
    'numPerms', nPerms_Full, ...  % Small N
    'parallel', true, ...
    'verbose', false);
time_full_sample = toc(timer_full);

% 3. Extrapolate to target permutation count
time_full_est = time_full_sample * (nPerms_Static / nPerms_Full);
speedup_factor = time_full_est / time_static;

fprintf('   Full LME refit (Extrapolated for %d): %.2f s\n', nPerms_Static, time_full_est);
fprintf('   >> SPEEDUP FACTOR: %.1f x <<\n', speedup_factor);

%% 4. Analysis & Visualization (Figure 2)

% Convert to vectors
all_R2    = [results.corr].^2;
all_Slope = [results.slope];
all_MAD   = [results.MAD];

% Identify Median Dataset (closest to median R2)
medianR2 = median(all_R2);
[~, idxBest] = min(abs(all_R2 - medianR2));

fprintf('\n=== Manuscript Reporting Statistics (N=%d) ===\n', nDatasets);
fprintf('R^2:        Mean = %.5f | Min = %.5f\n', mean(all_R2), min(all_R2));
fprintf('Slope:      Mean = %.5f | Range = [%.5f, %.5f] | SD = %.5f\n', mean(all_Slope), min(all_Slope), max(all_Slope), std(all_Slope));
fprintf('Intercept:  Mean = %.5f | SD = %.5f\n', mean([results.intercept]), std([results.intercept]));
fprintf('MAD:        Mean = %.5f | SD = %.5f\n', mean(all_MAD), std(all_MAD));
fprintf('==============================================\n');

% --- Figure Setup (Page Width ~18cm) ---
figWidth  = 18;   
figHeight = 6;    
fontSize  = 9;    
fontName  = 'Arial';

f = figure('Name', 'Fig 2: Algorithmic Validation', 'Color', 'w', 'Units', 'centimeters', 'Position', [5 5 figWidth figHeight]);

% Layout Constants (Normalized Units)
% To make Panel A physically square: Height_Norm * FigHeight = Width_Norm * FigWidth
h_panel = 0.65;              % Height of panels (65% of figure)
w_panel = h_panel * (figHeight / figWidth); % Width calculated to be square (approx 0.21)
b_panel = 0.18;              % Bottom margin
l_A     = 0.07;              % Left margin for A
l_C     = 0.75;              % Left edge of C

% Calculate space available for B between A and C
start_B = l_A + w_panel + 0.07; % Gap after A
end_B   = l_C - 0.1;            % Gap before C

% Split B into two equal sub-panels
gap_sub = 0.05;              % Small gap between Slope and MAD
w_sub   = (end_B - start_B - gap_sub) / 2;

l_B1    = start_B;           % Start of Slope panel
l_B2    = l_B1 + w_sub + gap_sub; % Start of MAD panel
pos_C = [l_C, b_panel, w_panel*1.2, h_panel]; % C is slightly wider

% --- Panel A: Identity Plot ---
ax1 = axes('Position', [l_A, b_panel, w_panel, h_panel]);

t_g = batch_T_full{idxBest};
t_f = batch_T_static{idxBest};

% Scatter: Blue 
scatter(t_g, t_f, 10, [0 0.447 0.741], 'Filled', 'MarkerFaceAlpha', 0.5);
hold on;

% Identity Line: Dark Gray 
minVal = min([t_g, t_f]);
maxVal = max([t_g, t_f]);
plot([minVal maxVal], [minVal maxVal], 'Color', [0.4 0.4 0.4], 'LineWidth', 1.5, 'LineStyle', '--');

% Formatting
% Note: Interpreter 'tex' is required for {\it...} to render correctly
title('Representative Dataset', 'FontWeight', 'normal', 'FontSize', fontSize, 'FontName', fontName);

xlabel('Full LME {\itt} (Timepoints)', 'FontName', fontName, 'FontSize', fontSize, 'Interpreter', 'tex');
ylabel('Static-V {\itt}-statistic', 'FontName', fontName, 'FontSize', fontSize, 'Interpreter', 'tex');
grid on;
set(gca, 'FontSize', fontSize, 'FontName', fontName, 'LineWidth', 0.75, 'Box', 'off', ...
    'TickLabelInterpreter', 'tex', 'XMinorTick', 'on', 'YMinorTick', 'on');
xlim([minVal maxVal]); ylim([minVal maxVal]);

add_panel_label(ax1, 'A');

% --- Panel B: Batch Fidelity Metrics (Split) ---

% Sub-panel B1: Slope
ax2a = axes('Position', [l_B1, b_panel, w_sub, h_panel]);

% 1. Raw Data: Light gray swarm to show all N=25 points
swarmchart(ones(size(all_Slope)), all_Slope, 8, ...
    'MarkerFaceColor', [0.7 0.7 0.7], 'MarkerEdgeColor', 'none', ...
    'MarkerFaceAlpha', 0.5, 'XJitterWidth', 0.6);
hold on;

% 2. Summary: Mean and Standard Deviation (Blue)
errorbar(1, mean(all_Slope), std(all_Slope), ...
    'Color', [0 0.447 0.741], 'LineWidth', 1.5, 'CapSize', 0, ...
    'Marker', 'o', 'MarkerSize', 6, 'MarkerFaceColor', [0 0.447 0.741]);

yline(1.0, 'Color', [0.7 0.7 0.7], 'LineWidth', 1.5); 
ylim([0.92 1.08]);
xlim([0.5 1.5]);
grid on;
set(ax2a, 'FontSize', fontSize, 'FontName', fontName, 'LineWidth', 0.75, 'Box', 'off', ...
    'ActivePositionProperty', 'position', 'XTick', 1, 'XTickLabel', {'Slope'});

% Add 'B' Label to the far left of the group
add_panel_label(ax2a, 'B');

% Sub-panel B2: MAD
ax2b = axes('Position', [l_B2, b_panel, w_sub, h_panel]);

% 1. Raw Data: Light gray swarm
swarmchart(ones(size(all_MAD)), all_MAD, 8, ...
    'MarkerFaceColor', [0.7 0.7 0.7], 'MarkerEdgeColor', 'none', ...
    'MarkerFaceAlpha', 0.5, 'XJitterWidth', 0.6);
hold on;

% 2. Summary: Mean and Standard Deviation
errorbar(1, mean(all_MAD), std(all_MAD), ...
    'Color', [0 0.447 0.741], 'LineWidth', 1.5, 'CapSize', 0, ...
    'Marker', 'o', 'MarkerSize', 6, 'MarkerFaceColor', [0 0.447 0.741]);

yline(0.0, 'Color', [0.7 0.7 0.7], 'LineWidth', 1.5); 

% Auto-scale MAD y-axis
ymax_mad = max(all_MAD) * 1.5;
if ymax_mad == 0, ymax_mad = 0.01; end
ylim([0, ymax_mad]); 
xlim([0.5 1.5]);

grid on;
set(ax2b, 'FontSize', fontSize, 'FontName', fontName, 'LineWidth', 0.75, 'Box', 'off', ...
    'ActivePositionProperty', 'position', 'XTick', 1, 'XTickLabel', {'MAD'});

% --- Panel C: Computational Efficiency ---
ax3 = axes('Position', pos_C);

% Data: [Static-V, Full LME]
times = [time_static, time_full_est];
b = bar(1:2, times, 0.7);
b.FaceColor = 'flat';
b.CData(1,:) = [0 0.447 0.741]; % Blue for Static-V
b.CData(2,:) = [0.4 0.4 0.4];   % Gray for Full LME

% Log scale for time
set(gca, 'YScale', 'log');
ylim([min(times)*0.5, max(times)*5]); % Space for label

% Annotations
% Speedup Label above the bars
text(1.5, max(times)*4.1, sprintf('%.0fx faster', speedup_factor), ...
    'HorizontalAlignment', 'center', ...
    'FontWeight', 'bold', 'FontSize', fontSize, 'FontName', fontName, 'Interpreter', 'tex');

% Text labels on top of bars (Seconds/Hours)
text(1, time_static*1.2, sprintf('%.0f s', time_static), ...
    'HorizontalAlignment', 'center', 'VerticalAlignment', 'bottom', 'FontSize', 8);

% Format Full LME label (Seconds vs Minutes vs Hours)
if time_full_est > 3600
    lab = sprintf('~%.1f hr', time_full_est/3600);
elseif time_full_est > 60
    lab = sprintf('~%.1f min', time_full_est/60);
else
    lab = sprintf('~%.0f s', time_full_est);
end
text(2, time_full_est*1.2, lab, ...
    'HorizontalAlignment', 'center', 'VerticalAlignment', 'bottom', 'FontSize', 8);

% Formatting
ylabel('Computation Time (s)', 'FontName', fontName, 'FontSize', fontSize, 'Interpreter', 'tex');
xticklabels({'Static-V', 'Full LME'});
grid on;

set(ax3, 'YScale', 'log', ...
         'YTick', 10.^(0:4), ...            % Major lines at 1, 10, 100, 1000, 10000
         'YMinorGrid', 'on', ...            % Keep the minor grid
         'YMinorTick', 'on');               % Ensure minor ticks are active

% Final visual polish: make the grid lines subtler
ax3.GridColor = [0.8 0.8 0.8];              % Light gray major grid
ax3.MinorGridColor = [0.9 0.9 0.9];         % Even lighter gray minor grid
ax3.MinorGridAlpha = 0.5;                   % Increase transparency of minor lines

% Reapply panel position after axis formatting
set(ax3, 'Position', pos_C, ...
         'FontSize', fontSize, ...
         'FontName', fontName, ...
         'LineWidth', 0.75, ...
         'Box', 'off', ...
         'TickLabelInterpreter', 'tex', ...
         'ActivePositionProperty', 'position');

add_panel_label(ax3, 'C');

%% 5. Export for Publication
if settings.exportFigures
    % Define full file paths
    pdfPath = fullfile(exportDir, [baseFileName '.pdf']);
    tifPath = fullfile(exportDir, [baseFileName '.tif']);

    fprintf('\nExporting journal-ready figures to:\n   %s\n', exportDir);

    % Ensure the figure is fully rendered before capture
    drawnow; 

    % 1. Export as a vector-based PDF
    % 'ContentType', 'vector' keeps text/lines sharp regardless of zoom.
    % 'BackgroundColor', 'none' ensures transparency for typesetting.
    exportgraphics(f, pdfPath, ...
        'ContentType', 'vector', ...
        'BackgroundColor', 'none');

    % 2. TIFF Export at 300 DPI
    exportgraphics(f, tifPath, ...
        'Resolution', 300);

    fprintf('Done. Figure exported as PDF (Vector) and TIFF (300 DPI).\n');
else
    fprintf('\nFigure export disabled in settings. Skipping figure save.\n');
end

% --- Helper: Publication Style Labeling ---
function add_panel_label(ax, labelChar)
    % Places bold label in top-left, normalized units
    text(ax, -0.25, 1.1, labelChar, 'Units', 'normalized', ...
        'FontSize', 12, 'FontWeight', 'bold', 'FontName', 'Arial', 'Interpreter', 'tex');
end